# Generated by Django 4.2.7 on 2023-11-18 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='supplier',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
