# Generated by Django 4.2.7 on 2023-11-20 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0002_alter_ingredient_supplier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='quantity_unit',
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='price_unit',
            field=models.CharField(choices=[('liter', 'Liter'), ('kilogram', 'Kilogram')], default='kilogram', max_length=8),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='supplier',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
