# Generated by Django 4.2.7 on 2023-11-26 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0003_remove_ingredient_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='price',
            field=models.FloatField(help_text='The value is in dollar'),
        ),
    ]
