# Generated by Django 4.2.7 on 2023-11-28 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0006_alter_ingredient_recipe_appearance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='supplier',
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='price',
            field=models.FloatField(help_text='The value is in dollar. Add the average price of the ingredient.Measures are in "kilogram" and "liter".'),
        ),
    ]
