# Generated by Django 4.2.7 on 2024-02-09 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0008_ingredient_pic_alter_ingredient_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='pic',
        ),
    ]
