# Generated by Django 4.2.7 on 2023-11-18 19:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=120)),
                ('name', models.CharField(max_length=120)),
                ('email', models.CharField(max_length=120)),
                ('birthday', models.DateField()),
                ('created_recipes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_recipes', to='recipes.recipe')),
                ('favorite_recipes', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='favorite_recipes', to='recipes.recipe')),
                ('username', models.OneToOneField(max_length=120, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
