# Generated by Django 4.2.7 on 2023-11-26 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_rename_creator_recipe_creator_id_and_more'),
        ('users', '0005_remove_user_created_recipes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='favorite_recipes',
        ),
        migrations.AddField(
            model_name='user',
            name='favorite_recipes_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='recipes.recipe'),
        ),
    ]
