# Generated by Django 4.2.7 on 2023-11-26 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_user_favorite_recipes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='favorite_recipes_id',
            new_name='favorite_recipes',
        ),
    ]
