# Generated by Django 4.2.7 on 2023-11-28 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_user_favorite_recipes_user_favorite_recipes'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default='no_picture.jpg', upload_to='users'),
        ),
    ]
