# Generated by Django 4.2.7 on 2023-12-17 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_remove_recipe_creator_id_recipe_creator_and_more'),
        ('users', '0013_alter_user_favorite_recipes'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created_recipes',
            field=models.ManyToManyField(blank=True, editable=False, related_name='created_recipes', to='recipes.recipe'),
        ),
        migrations.AlterField(
            model_name='user',
            name='favorite_recipes',
            field=models.ManyToManyField(blank=True, editable=False, related_name='favorite_recipes', to='recipes.recipe'),
        ),
    ]
