# Generated by Django 4.2.7 on 2024-02-06 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_user_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='favorite_recipes',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_info',
        ),
    ]
