# Generated by Django 4.2.7 on 2024-02-06 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_alter_user_user_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_info',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
