# Generated by Django 4.2.7 on 2024-02-09 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_alter_user_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_picture',
        ),
    ]
