# Generated by Django 4.2.7 on 2023-11-27 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_recipe_recipe_cost_alter_recipe_difficulty'),
        ('ingredients', '0004_alter_ingredient_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='price_unit',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='ingredient_unit_type',
            field=models.CharField(choices=[('liter', 'Liter'), ('kilogram', 'Kilogram')], default='kilogram', max_length=8),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='recipe_appearance',
            field=models.ManyToManyField(blank=True, null=True, to='recipes.recipe'),
        ),
    ]
