# Generated by Django 4.2.7 on 2023-11-27 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_alter_recipe_ingredient_quantities_and_more'),
        ('ingredients', '0005_remove_ingredient_price_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='recipe_appearance',
            field=models.ManyToManyField(blank=True, to='recipes.recipe'),
        ),
    ]
