# Generated by Django 4.2.7 on 2023-11-28 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0007_remove_ingredient_supplier_alter_ingredient_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='pic',
            field=models.ImageField(default='no_picture.jpg', upload_to='ingredients'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='price',
            field=models.FloatField(help_text='The value is in dollar. Add the average price of the ingredient. Measures are in "kilogram" and "liter".'),
        ),
    ]
