# Generated by Django 4.2.7 on 2023-11-19 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_password_alter_user_favorite_recipes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_recipes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='favorite_recipes',
            field=models.TextField(blank=True),
        ),
    ]
