# Generated by Django 4.2.7 on 2023-11-20 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_created_recipes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='created_recipes',
        ),
        migrations.AlterField(
            model_name='user',
            name='favorite_recipes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
