# Generated by Django 4.2.7 on 2023-11-26 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_rename_creator_recipe_creator_id_and_more'),
        ('users', '0007_rename_favorite_recipes_id_user_favorite_recipes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='favorite_recipes',
        ),
        migrations.AddField(
            model_name='user',
            name='favorite_recipes',
            field=models.ManyToManyField(blank=True, to='recipes.recipe'),
        ),
    ]
