# Generated by Django 4.2.7 on 2023-11-26 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_alter_recipe_creator_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredient_quantities',
            field=models.TextField(help_text='Add quantities pf the ingredients in the format: (100, gram), (50, milliliter)', max_length=2000, null=True),
        ),
    ]
