# Generated by Django 4.2.7 on 2023-11-27 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0005_remove_ingredient_price_unit_and_more'),
        ('recipes', '0008_recipe_recipe_cost_alter_recipe_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredient_quantities',
            field=models.TextField(help_text='Add quantities of the ingredients in the format: (100, gram), (50, milliliter)', max_length=2000, null=True),
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(help_text='Enter ingredients at the Ingredient table first.', to='ingredients.ingredient'),
        ),
    ]
