# Generated by Django 4.2.7 on 2023-12-08 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_recipe_recipe_directions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='difficulty',
            field=models.CharField(blank=True, editable=False, max_length=12, null=True),
        ),
    ]
