# Generated by Django 4.2.7 on 2023-12-17 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_user_favorite_recipes'),
        ('recipes', '0012_alter_recipe_difficulty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='creator_id',
            new_name='creator',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='creator',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='users.user'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredient_quantities',
            field=models.TextField(help_text='Add quantities of the ingredients (value will be gram or milliliter based on the ingredient.) Write in quantities separated with comma and space (, ): Example: 100, 50, 200', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_cost',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
    ]
