# Generated by Django 4.2.7 on 2023-11-20 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_recipe_creator_alter_recipe_ingredients'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='creator',
            new_name='creator_id',
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredient_quantities',
            field=models.TextField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(max_length=2000),
        ),
    ]
