# Generated by Django 4.2.7 on 2023-11-26 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_user_favorite_recipes_user_favorite_recipes'),
        ('recipes', '0005_rename_creator_recipe_creator_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='creator_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.user'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredient_quantities',
            field=models.TextField(help_text='Add quantities pf the ingredients in the format: (100, "gram"), (50, "milliliter")', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(help_text='Enter ingredients, separated by comma and space', max_length=2000),
        ),
    ]
