# Generated by Django 4.2.7 on 2023-11-27 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_alter_recipe_ingredient_quantities'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recipe_cost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='difficulty',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
