# Generated by Django 4.2.7 on 2023-12-17 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0017_alter_recipe_creator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='creator',
            new_name='creator_id',
        ),
    ]
