# Generated by Django 4.2.7 on 2023-12-17 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0018_rename_creator_recipe_creator_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='creator_id',
            new_name='creator',
        ),
    ]
