# Generated by Django 4.2.7 on 2024-02-03 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_user_profile_pic'),
        ('recipes', '0021_alter_recipe_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.user'),
        ),
    ]
