# Generated by Django 4.2.7 on 2024-02-09 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0023_alter_recipe_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='pic',
        ),
    ]
